# Task 1
Table

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
# 1. Load the dataset

data = pd.read_csv (r"C:\Users\arund\Downloads\Dataset  (1).csv")

data.head ()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
# Total number of restaurants
total = len(data)

# Percentage offering table booking
table_booking_percent = (data['Has Table booking'].str.lower() == "yes").mean() * 100

# Percentage offering online delivery
online_delivery_percent = (data['Has Online delivery'].str.lower() == "yes").mean() * 100

print(f"Percentage of restaurants offering table booking: {table_booking_percent:.2f}%")
print(f"Percentage of restaurants offering online delivery: {online_delivery_percent:.2f}%")

Percentage of restaurants offering table booking: 12.12%
Percentage of restaurants offering online delivery: 25.66%

In [7]:
# Clean column values
data['Has Table booking'] = data['Has Table booking'].str.strip().str.lower()

# Average rating for restaurants WITH table booking
avg_with_booking = data[data['Has Table booking'] == 'yes']['Aggregate rating'].mean()

# Average rating for restaurants WITHOUT table booking
avg_without_booking = data[data['Has Table booking'] == 'no']['Aggregate rating'].mean()

print(f"Average rating (with table booking): {avg_with_booking:.2f}")
print(f"Average rating (without table booking): {avg_without_booking:.2f}")

Average rating (with table booking): 3.44
Average rating (without table booking): 2.56

In [8]:
# Standardize values
data['Has Online delivery'] = data['Has Online delivery'].str.strip().str.lower()

# Group by price range and calculate percentage offering online delivery
online_delivery_by_price = (
    data.groupby("Price range")["Has Online delivery"]
      .apply(lambda x: (x == "yes").mean() * 100)
      .reset_index()
)

online_delivery_by_price.columns = ["Price Range", "Online Delivery (%)"]

print("Percentage of restaurants offering online delivery by price range:")
print(online_delivery_by_price)

Percentage of restaurants offering online delivery by price range:
   Price Range  Online Delivery (%)
0            1            15.774077
1            2            41.310633
2            3            29.190341
3            4             9.044369

# Task 2
Price Range Analysis

In [10]:
# Find the most common price range
most_common_price = data['Price range'].mode()[0]

print(f"The most common price range is: {most_common_price}")

The most common price range is: 1

In [11]:
# 1. AVERAGE RATING BY PRICE RANGE

avg_rating_by_price = (
    data.groupby("Price range")["Aggregate rating"]
    .mean()
    .reset_index()
)

print("Average Rating for Each Price Range:")
print(avg_rating_by_price)

Average Rating for Each Price Range:
   Price range  Aggregate rating
0            1          1.999887
1            2          2.941054
2            3          3.683381
3            4          3.817918

In [12]:
# 2. IDENTIFY COLOR OF HIGHEST AVERAGE RATING

# Find price range with highest average rating
best_price_range = avg_rating_by_price.loc[
    avg_rating_by_price["Aggregate rating"].idxmax(), "Price range"
]

# Get all rows with this price range
subset = data[data["Price range"] == best_price_range]

# Find the most common rating color for this price range
most_common_color = subset["Rating color"].mode()[0]

print(f"\nPrice range with highest average rating: {best_price_range}")
print(f"Color representing this price range: {most_common_color}")

Price range with highest average rating: 4
Color representing this price range: Yellow

# Task 3
Feature Engineering

In [13]:
# 1. LENGTH OF RESTAURANT NAME

data["Restaurant_Name_Length"] = data["Restaurant Name"].astype(str).apply(len)


# 2. LENGTH OF ADDRESS

data["Address_Length"] = data["Address"].astype(str).apply(len)


# 3. WORD COUNT IN RESTAURANT NAME

data["Restaurant_Name_WordCount"] = data["Restaurant Name"].astype(str).apply(lambda x: len(x.split()))


# 4. WORD COUNT IN ADDRESS

data["Address_WordCount"] = data["Address"].astype(str).apply(lambda x: len(x.split()))


# 5. NUMBER OF CUISINES OFFERED

data["Cuisine_Count"] = data["Cuisines"].astype(str).apply(lambda x: len(x.split(", ")))


# 6. DOES THE RESTAURANT NAME CONTAIN SPECIAL CHARACTERS?

data["Has_SpecialChar"] = data["Restaurant Name"].astype(str).apply(
    lambda x: any(not char.isalnum() and not char.isspace() for char in x)
)

# Show first few rows with new features
data.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Aggregate rating,Rating color,Rating text,Votes,Restaurant_Name_Length,Address_Length,Restaurant_Name_WordCount,Address_WordCount,Cuisine_Count,Has_SpecialChar
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,4.8,Dark Green,Excellent,314,16,71,3,10,3,False
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,4.5,Dark Green,Excellent,591,16,67,2,10,1,False
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,4.4,Green,Very Good,270,22,56,4,8,4,True
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,4.9,Dark Green,Excellent,365,4,70,1,10,2,False
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,4.8,Dark Green,Excellent,229,11,64,2,9,2,False

In [14]:
# Standardize values to lowercase (important!)
data["Has Table booking"] = data["Has Table booking"].str.lower().str.strip()
data["Has Online delivery"] = data["Has Online delivery"].str.lower().str.strip()

# Encode Yes/No values into binary (1 or 0)
data["Table_Booking_Flag"] = data["Has Table booking"].map({"yes": 1, "no": 0})
data["Online_Delivery_Flag"] = data["Has Online delivery"].map({"yes": 1, "no": 0})

# Show first few rows
print(data[["Has Table booking", "Table_Booking_Flag",
          "Has Online delivery", "Online_Delivery_Flag"]].head())

  Has Table booking  Table_Booking_Flag Has Online delivery  \
0               yes                   1                  no
1               yes                   1                  no
2               yes                   1                  no
3                no                   0                  no
4               yes                   1                  no

   Online_Delivery_Flag
0                     0
1                     0
2                     0
3                     0
4                     0